apiVersion: v2
name: pedido-app
description: "Sistema de gestión de pedidos (PostgreSQL + Spring Boot + Frontend)"
type: application
version: 0.1.6
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    alias: db
    version: 15.5.18
    repository: "https://charts.bitnami.com/bitnami"
    condition: db.enabled
