replicaCount:
  backend: 1
  frontend: 1
image:
  backend:
    repository: tuusuario/pedido-backend
    tag: "dev"
    pullPolicy: IfNotPresent
  frontend:
    repository: tuusuario/pedido-frontend
    tag: "dev"
    pullPolicy: IfNotPresent
service:
  backend:
    type: ClusterIP
    port: 8080
  frontend:
    type: ClusterIP
    port: 80
ingress:
  enabled: true
  className: "nginx"
  host: "dev.127.0.0.1.sslip.io"
  tls:
    enabled: false
resources:
  backend:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  frontend:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi
hpa:
  backend:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
db:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: db-credentials
    username: pedido
    database: pedidos
  primary:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "do-block-storage"
secrets:
  db:
    postgresPassword: "postgres-dev-123"
    userPassword: "pedido-dev-123"
