apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.db.postgresPassword | quote }}
  password: {{ .Values.secrets.db.userPassword | quote }}
